%%%-------------------------------------------------------------------
%%% @author Redpate <redpate@hotmail.com>
%%% @copyright (C) 2016, Redpate
%%% @doc
%%% Main supervisor module, make all stuff runing longer xD
%%% @end
%%% Created : 20 Feb 2016 by Redpate
%%% Copyright © 2016 Redpate
%%%
%%% Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
%%%
%%% The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
%%%
%%% THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
%%%-------------------------------------------------------------------
-module(scout_probe_sup).

-behaviour(supervisor).

-include("config.hrl").
%% API
-export([start_link/0]).

%% Supervisor callbacks
-export([init/1]).


%% ===================================================================
%% API functions
%% ===================================================================

start_link() ->
  supervisor:start_link({local, ?MODULE}, ?MODULE, []).

%% ===================================================================
%% Supervisor callbacks
%% ===================================================================

init([]) ->
  inets:start(), %% should be stardet already, but let call it one more time
  sqlite3:open(?DB_NAME,[{file, "sqlite-latest.sqlite"}]), %% Static export in sqlite
  {ok, { {one_for_one, 5, 10}, [
    {km_collector, {km_collector, collector, []}, permanent, brutal_kill, worker, []}, %% collect killmails from zkillboard
    {tracker_sup, {tracker_sup, start_link, []}, permanent, brutal_kill, supervisor, [tracker_sup]}, %% manage all trckers
    {event_pool, {event_pool, start_link, []}, permanent, brutal_kill, worker, []}, %% manage all events generated by killmails
    {router_sup, {router_sup, start_link, []}, permanent, 5000, supervisor, [router_sup]}, % keeps routers runing
    {sov, {sov, start_link, []}, permanent, 5000, worker, []} %% manage sov changes
  ]} }.
